export const CATEGORIES_FETCHED = 'CATEGORIES_FETCHED';
export const CATEGORIES_FETCHED_FAILURE = 'CATEGORIES_FETCHED_FAILURE';

export const SAVE_CATEGORY_STARTED = 'SAVE_CATEGORY_STARTED';
export const SAVE_CATEGORY_COMPLETED = 'SAVE_CATEGORY_COMPLETED';
export const SAVE_CATEGORY_ERROR = 'SAVE_CATEGORY_ERROR';

export const EDIT_CATEGORY_STARTED = 'EDIT_CATEGORY_STARTED';

export const UPDATE_CATEGORY_STARTED = 'UPDATE_CATEGORY_STARTED';
export const UPDATE_CATEGORY_COMPLETED = 'UPDATE_CATEGORY_COMPLETED';
export const UPDATE_CATEGORY_ERROR = 'UPDATE_CATEGORY_ERROR';

export const DELETE_CATEGORY_STARTED = 'DELETE_CATEGORY_STARTED';
export const DELETE_CATEGORY_COMPLETED = 'DELETE_CATEGORY_COMPLETED';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR';

export const CATEGORY_FIELD_UPDATED = 'CATEGORY_FIELD_UPDATED';

export const CATEGORY_UPDATED = 'CATEGORY_UPDATED';

export const CLEAR_CATEGORY_EDITOR = 'CLEAR_CATEGORY_EDITOR';

export const CATEGORY_SAVE_ERROR = 'CATEGORY_SAVE_ERROR';

export const CATEGORY_FETCHED = 'CATEGORY_FETCHED';

export const CATEGORY_STATE_CLEARED = 'CATEGORY_STATE_CLEARED';

export const CATEGORY_ADD_MODAL_OPENED = 'CATEGORY_ADD_MODAL_OPENED';

export const CATEGORY_ADD_MODAL_RESET = 'CATEGORY_ADD_MODAL_RESET';
